services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://postgres:5432/reals
      DATABASE_USERNAME: reals
      DATABASE_PASSWORD: reals
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/reals
      SPRING_DATASOURCE_USERNAME: reals
      SPRING_DATASOURCE_PASSWORD: reals
      FIREBASE_SERVICE_ACCOUNT_PATH: /run/secrets/firebase-service-account.json
      SCHEDULER_ENABLED: "false"
    volumes:
      - ./secrets/reals-backend-firebase-credentials-dev.json:/run/secrets/firebase-service-account.json:ro
