package com.reals.backend.service.exception

enum class DomainErrorCode {
    ACCOUNT_DELETION_FINALIZED,
    ACCOUNT_PENDING_DELETION,
    ACTIVE_CONNECTION_LIMIT_REACHED,
    ACTIVE_MATCH_LIMIT_REACHED,
    ACTIVE_PENALTY,
    CHAT_DECISION_ALREADY_SUBMITTED,
    CHAT_DECISION_NOT_AVAILABLE,
    CHAT_EXIT_REQUEST_ALREADY_PENDING,
    CHAT_EXIT_REQUEST_NOT_AVAILABLE,
    CHAT_EXIT_REQUEST_NOT_FOUND,
    CHAT_EXPIRED,
    CHAT_MESSAGE_INVALID,
    CHAT_MIN_MESSAGES_REQUIRED,
    CHAT_MUTUAL_CANCELLATION_PENDING,
    CHAT_NOT_AVAILABLE,
    CHAT_NOT_FOUND,
    INVALID_MATCH_FILTERS,
    INVALID_PROFILE_BIRTH_DATE,
    INVALID_SEARCH_LOCATION,
    PHOTO_POSITION_INVALID,
    PHOTO_POSITION_OCCUPIED,
    PROFILE_ALREADY_EXISTS,
    PROFILE_FULL_BODY_PHOTO_REQUIRED,
    PROFILE_NOT_FOUND,
    PROFILE_NOT_ACTIVE,
    PROFILE_NOT_ACTIVATABLE,
    PROFILE_PERSON_PHOTO_REQUIRED,
    PROFILE_PHOTO_LIMIT_REACHED,
    PROFILE_PHOTOS_REQUIRED,
    PROFILE_REQUIRED,
    SCHEDULING_CANNOT_ACCEPT_OWN_PROPOSAL,
    SCHEDULING_EXPIRED,
    SCHEDULING_INVALID_PROPOSALS,
    SCHEDULING_NEGOTIATION_NOT_FOUND,
    SCHEDULING_NOT_AVAILABLE,
    SCHEDULING_PROPOSALS_ALREADY_SUBMITTED,
    SCHEDULING_PROPOSAL_NOT_AVAILABLE,
    SCHEDULING_ROUND_NOT_REJECTABLE,
    SECOND_CHAT_EXPIRED,
    SECOND_CHAT_NOT_AVAILABLE,
    SECOND_CHAT_NOT_AVAILABLE_YET,
    VISUAL_REVIEW_PARTNER_MESSAGE_NOT_READ,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    INVALID_PROFILE_PHOTO,
    PROFILE_PHOTO_NOT_FOUND,
    PROFILE_PHOTO_UPLOAD_FAILED,
}

sealed class DomainException(
    val code: DomainErrorCode,
    message: String
) : RuntimeException(message)

class DomainBadRequestException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)

class DomainConflictException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)

class DomainNotFoundException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)
