package com.reals.backend.service.exception

enum class DomainErrorCode {
    ACCOUNT_DELETION_FINALIZED,
    ACCOUNT_PENDING_DELETION,
    ACTIVE_CONNECTION_LIMIT_REACHED,
    ACTIVE_MATCH_LIMIT_REACHED,
    ACTIVE_PENALTY,
    CHAT_DECISION_ALREADY_SUBMITTED,
    CHAT_DECISION_NOT_AVAILABLE,
    CHAT_ABANDONED,
    CHAT_EXIT_REQUEST_ALREADY_PENDING,
    CHAT_EXIT_REQUEST_NOT_AVAILABLE,
    CHAT_EXIT_REQUEST_NOT_FOUND,
    CHAT_EXPIRED,
    FIRST_CHAT_GUIDANCE_COMPLETED,
    FIRST_CHAT_GUIDANCE_NEXT_ALREADY_REQUESTED,
    FIRST_CHAT_GUIDANCE_NOT_FOUND,
    FIRST_CHAT_GUIDANCE_PARTICIPATION_REQUIRED,
    CHAT_MESSAGE_INVALID,
    CHAT_MIN_MESSAGES_REQUIRED,
    CHAT_MUTUAL_CANCELLATION_PENDING,
    CHAT_NOT_AVAILABLE,
    CHAT_NOT_FOUND,
    EMAIL_NOT_VERIFIED,
    IDENTITY_VERIFICATION_PROVIDER_ERROR,
    INVALID_MATCH_FILTERS,
    INVALID_PROFILE_BIRTH_DATE,
    INVALID_SEARCH_LOCATION,
    LEGAL_DOCUMENT_ACTION_INVALID,
    LEGAL_DOCUMENT_NOT_FOUND,
    LEGAL_DOCUMENT_VERSION_NOT_CURRENT,
    PHOTO_POSITION_INVALID,
    PHOTO_POSITION_OCCUPIED,
    PROFILE_ALREADY_EXISTS,
    PROFILE_IDENTITY_VERIFICATION_REQUIRED,
    PROFILE_FULL_BODY_PHOTO_REQUIRED,
    PROFILE_NOT_FOUND,
    PROFILE_NOT_ACTIVE,
    PROFILE_NOT_ACTIVATABLE,
    PROFILE_PERSON_PHOTO_REQUIRED,
    PROFILE_PHOTO_LIMIT_REACHED,
    PROFILE_PHOTOS_REQUIRED,
    PROFILE_REQUIRED,
    SCHEDULING_CANNOT_ACCEPT_OWN_PROPOSAL,
    SCHEDULING_EXPIRED,
    SCHEDULING_INVALID_PROPOSALS,
    SCHEDULING_NEGOTIATION_NOT_FOUND,
    SCHEDULING_NOT_AVAILABLE,
    SCHEDULING_PROPOSALS_ALREADY_SUBMITTED,
    SCHEDULING_PROPOSAL_NOT_AVAILABLE,
    SCHEDULING_ROUND_NOT_REJECTABLE,
    SECOND_CHAT_EXPIRED,
    SECOND_CHAT_NOT_AVAILABLE,
    SECOND_CHAT_NOT_AVAILABLE_YET,
    VISUAL_REVIEW_EXPIRED,
    VISUAL_REVIEW_PARTNER_MESSAGE_NOT_READ,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    INVALID_PROFILE_PHOTO,
    PROFILE_PHOTO_NOT_FOUND,
    PROFILE_PHOTO_MODERATION_FAILED,
    PROFILE_PHOTO_MODERATION_NOT_APPROVED,
    PROFILE_PHOTO_REJECTED,
    PROFILE_PHOTO_UPLOAD_FAILED,
    SAFETY_REPORT_ALREADY_EXISTS,
    SAFETY_REPORT_ADMIN_CREATE_INVALID,
    SAFETY_REPORT_ALREADY_REVIEWED,
    SAFETY_REPORT_CONTEXT_INVALID,
    SAFETY_REPORT_NOT_FOUND,
    USER_BLOCK_SELF_NOT_ALLOWED,
    USER_PAIR_BLOCKED,
}

sealed class DomainException(
    val code: DomainErrorCode,
    message: String
) : RuntimeException(message)

class DomainBadRequestException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)

class DomainConflictException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)

class DomainNotFoundException(
    code: DomainErrorCode,
    message: String
) : DomainException(code, message)
